version: '2'

services:
  gerbo:
    container_name: gerbo
    build: ./docker/golang
    volumes:
     - ./:/go/src
    links:
     - mongo
    depends_on:
     - mongo
  mongo:
   container_name: mongo
   build: ./docker/mongo
   command: sh /var/www/build.sh
   volumes:
    - ./docker/mongo/:/var/www
   ports:
    - "127.0.0.1:27017:27017"